apiVersion: infra.loco.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  # TODO(user): Add fields here
