apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: {{ .Values.certManager.issuer.name }}
    namespace: cert-manager
spec:
    acme:
        email: {{ .Values.certManager.issuer.email | required "certManager.issuer.email is required" }}
        server: {{ .Values.certManager.issuer.server }}
        privateKeySecretRef:
            name: {{ .Values.certManager.issuer.name }}-key
        solvers:
            - dns01:
                  cloudflare:
                      apiTokenSecretRef:
                          name: cloudflare-api-token-secret
                          key: api-token
