apiVersion: v1
kind: Secret
metadata:
  name: env-config
  namespace: loco-system
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
