apiVersion: v1
kind: Secret
metadata:
  name: env-config
  namespace: loco-system
type: Opaque
stringData:
  GITLAB_PAT: {{.Values.secrets.env.GITLAB_PAT | quote}}
  GITLAB_PROJECT_ID: {{.Values.secrets.env.GITLAB_PROJECT_ID | quote}}
  GITLAB_TOKEN_NAME: {{.Values.secrets.env.GITLAB_TOKEN_NAME | quote}}
  GH_OAUTH_CLIENT_ID: {{.Values.secrets.env.GH_OAUTH_CLIENT_ID | quote}}
  GITLAB_URL: {{.Values.secrets.env.GITLAB_URL | quote}}
  GITLAB_REGISTRY_URL: {{.Values.secrets.env.GITLAB_REGISTRY_URL | quote}}
  GITLAB_DEPLOY_TOKEN_NAME: {{.Values.secrets.env.GITLAB_DEPLOY_TOKEN_NAME | quote}}
  APP_ENV: {{.Values.secrets.env.APP_ENV | quote}}
  LOG_LEVEL: {{.Values.secrets.env.LOG_LEVEL | quote}}
  PORT: {{.Values.secrets.env.PORT | quote}}
  GH_OAUTH_CLIENT_SECRET: {{.Values.secrets.env.GH_OAUTH_CLIENT_SECRET | quote}}
  GH_OAUTH_REDIRECT_URL: {{.Values.secrets.env.GH_OAUTH_REDIRECT_URL | quote}}
  GH_OAUTH_STATE: {{.Values.secrets.env.GH_OAUTH_STATE | quote}}
  DATABASE_URL: {{.Values.secrets.env.DATABASE_URL | quote}}
  JWT_SECRET: {{.Values.secrets.env.JWT_SECRET | quote}}
  REGISTRY_TAG: {{.Values.secrets.env.REGISTRY_TAG | quote}}
