apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: {{ .Release.Namespace }}
spec:
  infrastructure:
    {{- if .Values.global.cloudProvider.annotations }}
    annotations:
      {{- toYaml .Values.global.cloudProvider.annotations | nindent 6 }}
    {{- end }}
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: envoy-proxy
  gatewayClassName: eg
  listeners:
    - name: https
      hostname: {{ .Values.global.domain.wildcard | quote }}
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Release.Name }}-tls
            kind: Secret
            group: ""
    - name: http
      hostname: {{ .Values.global.domain.wildcard | quote }}
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy
  namespace: {{ .Release.Namespace }}
spec:
  telemetry:
    metrics:
      prometheus:
        disable: true
      enablePerEndpointStats: true
      enableRequestResponseSizesStats: true
      sinks:
        - type: OpenTelemetry
          openTelemetry:
            host: {{ .Values.global.observability.otelCollectorDeployment }}.{{ .Values.global.observability.namespace }}.svc.cluster.local
            port: 4317
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: enable-http3
  namespace: {{ .Release.Namespace }}
spec:
  http3: {}
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
