apiVersion: v1
kind: Service
metadata:
  name: loco-ui
  namespace: loco-system
spec:
  selector:
    app: loco-ui
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: loco-ui
      protocol: TCP
      port: 80
      targetPort: 8080
