apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: loco-cert
    namespace: loco-system
spec:
    secretName: loco-tls
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: "*.deploy-app.com"
    dnsNames:
        - "*.deploy-app.com"
        - "*.us-east-1.deploy-app.com"
        - "*.eu-west-1.deploy-app.com"
        - "*.staging.us-east-1.deploy-app.com"
        - "*.prod.us-east-1.deploy-app.com"
        - "*.staging.eu-west-1.deploy-app.com"
        - "*.prod.eu-west-1.deploy-app.com"
